
import Head from "next/head";
import { Inter } from "next/font/google";
import BarraNavegacion from "@/components/layout/header/BarraNavegacion";
import TituloPagina from "@/components/layout/header/TituloPagina";
import MainContainerCss from "@/components/pages/css/selectoCss";
import CssPage from "@/components/pages/css/contenidoCss";

const inter = Inter({ subsets: ["latin"] });

export default function Index_CSS() {
  return (
    <>
    <header>
      <Head>
       <TituloPagina titulo='CSS'>DOCUM</TituloPagina>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      </header>
      <main>
      <BarraNavegacion/>
      <MainContainerCss/>
      <CssPage/>
<div>
  <a href= "/css/Background">Background</a>
</div>
<br></br>
<div>
  <a href= "/html/border">Border</a>
</div>
<br></br>
</main> 
    </>
  );
}