
import Head from "next/head";
import { Inter } from "next/font/google";
import BarraNavegacion from "@/components/layout/header/BarraNavegacion";

const inter = Inter({ subsets: ["latin"] });

export default function Index_react() {
  return (
    <>
      <Head>
      <BarraNavegacion/>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      
    <h1> DOCUMENTACIÓN PROFESIONAL REACT</h1>
<div>
  <a href= "/react/componentes">Componentes</a>
</div>
<br></br>
<div>
<a href= "/react/hook">Hook</a>
</div>
<br></br>
</main> 
    </>
  );
}