import Head from "next/head";
import { Inter } from "next/font/google";
import BarraNavegacion from "@/components/layout/header/barraNavegacion";

const inter = Inter({ subsets: ["latin"] });

export default function Listas() {
  return (
    <>
   <Head>

           <title>Create Next App</title>
           <meta name="description" content="Generated by create next app" />
           <meta name="viewport" content="width=device-width, initial-scale=1" />
           <link rel="icon" href="/favicon.ico" />
   </Head>
   <body>
    <header></header>
           <main>
           <h1>Esto es una lista no ordenada</h1>
           <ul>
           <li>Esto</li>
           <li>es</li>
           <li>una</li>
           <li>lista no ordenada</li>
           </ul>

           <h1>Esto es una lista ordenada</h1>
           <ol>
           <li>Esto</li>
           <li>Es</li>
           <li>una</li>
           <li>lista ordenada</li>
           </ol>
           <div>
           <a href="/"> HOME</a>
           </div>
           </main>
           <footer></footer>
           </body>
    </>
  );
}