import Head from "next/head";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function BarraNavegacion() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <nav>
        <ul>
        <li><a href="/html/">HTML<img src="/html.png/"width="36" height="36"></img></a></li>
        <li><a href="/html">CSS<img src="/css.png/"width="36" height="36"></img></a></li>
        <li><a href="/html">Js<img src="/js.png/"width="36" height="36"></img></a></li>
        <li><a href="/html">TS<img src="/TS.png/" width="36" height="36"></img></a></li>
        <li><a href="/html">Angular<img src="/Angular.png/" width="36" height="36"></img></a></li>
        <li><a href="/react">React<img src="/react.png/" width="36" height="36"></img></a></li> 
      </ul> 
      </nav>
    </main>
    <footer>
    </footer>
    </>
  );
}