import Head from "next/head";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Imagenes() {
  return (
    <>
<Head>

         <title>Ejemplo de Buttom</title>
         <meta name="description" content="Generated by create next app" />
         <meta name="viewport" content="width=device-width, initial-scale=1" />
         <link rel="icon" href="/favicon.ico" />
</Head>
<body>
    <header></header>
     <main>
        <footer> </footer>

    
         <h1>Buttom </h1> 
         <h3>La etiqueta img sirve para insertar imagenes</h3>
         <p><h2> A continuación se muestra el codigo</h2></p>
         <div>
         <a href="/">HOME</a>
         </div>
         
    </main>
    <footer></footer>
    </body>
    </>
  );
}