
import Head from "next/head";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Index_html() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      
    <h1> DOCUMENTACIÓN PROFESIONAL HTML</h1>
<div>
  <a href= "/html/Encabezados">Encabezados</a>
</div>
<br></br>
<div>
  <a href= "/html/Parrafos">Parrafo</a>
</div>
<br></br>
<div>
  <a href= "/html/Listas">Listas</a>
</div>
<br></br>
<div>
  <a href= "/html/tablas">Tablas</a>
</div>
<br></br>
<div>
  <a href= "/html/imagenes">Imagenes</a>
</div>
<br></br>
<div>
  <a href= "/html/buttom">Buttom</a>
</div>
<br></br>
<div>
  <a href= "/html/formulario">Formulario</a>
</div>
</main> 
    </>
  );
}