import Head from "next/head";

export default function Html() {
  return (
    <>
      <Head>
        <title>HTML docu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>DOCUMENTACIÓN PROFESIONAL DE HTML</h1>
        <div>
          <a href="/html/encabezados">Encabezados</a>
        </div>
        <div>
          <a href="/html/parrafo">Parrafos</a>
        </div>
        <div>
          <a href="/html/listas">Listas</a>
        </div>
        <a
          href="./"
          title="El mejor lugar para encontrar más información acerca de la misión de Mozilla
          y cómo contribuir"
        >
          Home
        </a>
        <a href="./">/Home1</a>
        <a href="./">/Home2</a>
      </main>
    </>
  );
}