import Head from "next/head";
import BarraNavegacion from "../../home/header";

export default function ButtonHeader() {
    return (
      
      <Head>
<BarraNavegacion/>
         <title>Ejemplo de Buttom</title>
         <meta name="description" content="Generated by create next app" />
         <meta name="viewport" content="width=device-width, initial-scale=1" />
         <link rel="icon" href="/favicon.ico" />
</Head>
)
}