import BarraNavegacion from "@/components/pages/home/header";
import Head from "next/head";

export default function Formulario() {
  return (
    <>
     <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
     </Head>
     <BarraNavegacion/>
     <body>
        <header></header>
         <main>
         <h1>Formularios:</h1>
         <p><h4>Los formularios permiten a los usuarios la introducción de datos, que generalmente se envían a un servidor web para su procesamiento y almacenamiento</h4></p>
         
         <form action="/my-handling-form-page" method="post">
  <ul>
    <li>
      <label htmlFor="name">Nombre:</label>
      <input type="text" id="name" name="name" required />
    </li>
    <br></br>

    <li>
      <label htmlFor="email">Correo electrónico:</label>
      <input type="email" id="email" name="email" />
    </li>
    <br></br>

    <li>
      <label htmlFor="msg">Mensaje:</label>
      <textarea id="msg" name="user_message"></textarea>
    </li>
    <br></br>
    
    <li>
      <label htmlFor="Tu dia preferido del año">Dia favorito del año</label>
      <input type="date" id="tu dia preferido" name="data" required />
    </li>
  </ul>
</form>

<p>
                <label htmlFor="product">Producto</label>
                <select name="product" id="product">
                    <option value="libro">Calculadora</option>
                    <option value="lapiz">Gafas</option>
                    <option value="caña_pesca">vaso</option>
                    <option value="acuarela">ordenador</option>
                </select>
            </p>

         </main>
         <footer></footer>
         </body>  

    </>
  );
}