import Head from "next/head";
import { Inter } from "next/font/google";
import BarraNavegacion from "@/components/layout/header/BarraNavegacion";

const inter = Inter({ subsets: ["latin"] });

export default function Parrafos() {
  return (
    <>
     <Head>
   
         <title>Create Next App</title>
         <meta name="description" content="Generated by create next app" />
         <meta name="viewport" content="width=device-width, initial-scale=1" />
         <link rel="icon" href="/favicon.ico" />
     </Head>
     <body>
      <header></header>
         <main>
           <h1>Aprender a hacer un parrafo </h1> 
           <h2><p> Esto es un parrafo </p><p>Esto es otro </p></h2>
           <div>
            <a href="/">HOME</a>
         </div>
         </main>
         <footer> </footer>
         </body>
    </>
  );
}