import Head from "next/head";
import { Inter } from "next/font/google";
import Saludo from "@/components/layout/main/saludo";
import Contador from "@/components/pages/home/footer/contador";

const inter = Inter({ subsets: ["latin"] });

export default function index_page_principal() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <Saludo/>
        <ul>
        <li><a href="/html/">HTML<img src="/html.png/"width="36" height="36"></img></a></li>
        <li><a href="/css">CSS<img src="/css.png/"width="36" height="36"></img></a></li>
        <li><a href="/Js">Js<img src="/js.png/"width="36" height="36"></img></a></li>
        <li><a href="/Ts">TS<img src="/TS.png/" width="36" height="36"></img></a></li>
        <li><a href="/Angular">Angular<img src="/Angular.png/" width="36" height="36"></img></a></li>
        <li><a href="/React">React<img src="/react.png/" width="36" height="36"></img></a></li> 
      </ul> 
    </main>
    <footer>
      <Contador/>
    </footer>
    </>
  );
}
