import Head from "next/head";
import { Inter } from "next/font/google";
import styled from "styled-components";

const inter = Inter({ subsets: ["latin"] });
const Lista= styled.ul
`color: black;
fonst-size:20pag;
`
const NavBar= styled.nav
`Dysplay: flex;
justify-content: space-around;
`
const TextSpan = styled.span`
margin-left: 10px;
color: #059862;
&: hover {
color: black;
font-size: 25px;
}
transition: all 0.5s;
` 
const LinkA = styled.a`
text-decoration: none;
display: flex;
align-items: center;
flex-direction: row-reverse;
&: hover{
  color: black;
  font-size: 20px;
};
transition: all 0.5s;
`


export default function BarraNavegacion() {
  return (
     <div>
      <NavBar>
        <LinkA href ="/html/">
          <TextSpan>HTML</TextSpan>{" "}
          <img src="/html.png/"width="36" height="36"/>
        </LinkA>

        <LinkA href ="/CSS/">
          <TextSpan>CSS</TextSpan>{" "}
          <img src="/css.png/"width="36" height="36"/>
        </LinkA>

        <LinkA href ="/JS/">
          <TextSpan>JS</TextSpan>{" "}
          <img src="/js.png/"width="36" height="36" />
        </LinkA>

        <LinkA href ="/JS/">
          <TextSpan>JS</TextSpan>{" "}
          <img src="/js.png/"width="36" height="36" />
        </LinkA>

        <LinkA href ="/TS/">
          <TextSpan>TS</TextSpan>{" "}
          <img src="/TS.png/" width="36" height="36"/>
        </LinkA>

        <LinkA href ="/TS/">
          <TextSpan>TS</TextSpan>{" "}
          <img src="/Angular.png/" width="36" height="36"/>
        </LinkA>

      </NavBar>

     </div>
  );
  
     /*
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <nav>
          
          <NavBar>
      
        <li><a href="/html">Angular<></img></a></li>
        <li><a href="/react">React<img src="/react.png/" width="36" height="36"></img></a></li> 
      </Lista> 
      </NavBar>
      
      </nav>
    </main>
    <footer>
    </footer>
    </>
  );
}*/
}