import BarraNavegacion from "@/components/pages/home/header";
import Head from "next/head";

export default function Tablas() {
  return (
    <>
     <Head>
         <title>Create Next App</title>
         <meta name="description" content="Generated by create next app" />
         <meta name="viewport" content="width=device-width, initial-scale=1" />
         <link rel="icon" href="/favicon.ico" />
     </Head>
     <BarraNavegacion/>
     <body>
        <header></header>
         <main>
           <h1>Aprender a hacer una tabla </h1> 
           <h4><p> En primer lugar  la etiqueta table dará lugar a la tabla </p>
           <p>en segundo lugar usaremos thead que contendrá la cabecera de la tabla</p> 
           <p> en tercer lugar tr será una fila de la tabla</p>
           <p>en cuarto lugar con th haremos una columna</p>
           </h4>
           <h1><p> A continuación se muestra el código</p>
           <p></p>
           </h1>
           <h1><p> EJEMPLO:</p>
           </h1>

         <table border ={50}>
             <thead>
                <tr>
                    <th>Columna 1</th>
                    <th>Columna 2</th>
                    <th>Columna 3</th>
                    <th>Columna 4</th>
                </tr>
             </thead>
             <tbody>
                <tr>
                    <td> Dato1</td>
                    <td> Dato2</td>
                    <td> Dato3</td>
                    <td> Dato4</td>

                </tr>
            
            
            <tr>
                    <td> Dato1</td>
                    <td> Dato2</td>
                    <td> Dato3</td>
                    <td> Dato4</td>

                </tr>
            </tbody>
           
         </table>
         <div>
            <a href="/">HOME</a>
         </div>
        

         </main>
         <footer></footer>
         </body>  

    </>
  );
}